# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'hanami-2.0' do
  gem 'hanami', '2.0.0.rc1'
  gem 'hanami-router', '2.0.0.rc1'
  gem 'hanami-controller', '2.0.0.rc1'
end

if RUBY_VERSION < '3'
  appraise 'hanami-1.3' do
    gem 'hanami', '~> 1.3.5'
  end
end
